version: '3'
services:
  bootstrap:
    build: geth-node
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: --datadir=~/.ethereum/devchain --nodekeyhex=09f169e219c663b64691f8e39ee5e0877c9e6cd8d373daee26849cc4a7302047 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0" --mine
    volumes:
      - ./genesis/password:/root/genesis/password:ro
      - ./genesis/genesis.json:/root/genesis/genesis.json:ro
      - ./genesis/keystore:/root/.ethereum/devchain/keystore:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth:
    build: geth-node
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./genesis/password:/root/genesis/password:ro
      - ./genesis/genesis.json:/root/genesis/genesis.json:ro
      - ./genesis/keystore:/root/.ethereum/devchain/keystore:rw
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=456719 --rpc --bootnodes="enode://e68b4732ee9ec126e5e66c7a2e90346e093c92c83b750967d6a2d089d6fd9dacc1a04fbd54ca9aa2fee13b4d4de1c3ff68ea5aad1e8da3578bacdcf91edde0e7@1.29.82.155:30303?discport=4969" --mine'
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3000:3000"
